### ISSUE TITLE
Backend -> main app

### ISSUE THREAD

**Issue by ioFormigoni** [acremonezi/Projeto-Integrador-em-Computacao-II#13]
novo app dentro do projeto (o principal agora)

Desenvolvimento do modelo de acordo com o [Entity-Relationship-Model rev01](https://github.com/acremonezi/Projeto-Integrador-em-Computacao-II/tree/main/docs/data_models/high_level_conceptual)

**Comment by acremonezi** [comment]
I will Fix some errors.
