### ISSUE TITLE
Frontend -> index

### ISSUE THREAD

**Issue by ioFormigoni** [acremonezi/Projeto-Integrador-em-Computacao-II#30]
Create the index file (do not add any functionality yet).
follow UI/UX design (Projeto-Integrador-em-Computacao-II/docs/ux/)

**Comment by 2005869** [comment]
para quem for fazer essa issue, o index já está no app accounts assim como o base, atenção para os caminhos:

index.html ----> django_project/accounts/templates/accounts/index.html
base.html  ----> django_project/accounts/templates/account/base.html

Podem editar diretamente nesses arquivos, em qualquer app do projeto estender para:
{% extends 'account/base.html' %}
