### ISSUE TITLE
Frontend -> Main app

### ISSUE THREAD

**Issue by ioFormigoni** [acremonezi/Projeto-Integrador-em-Computacao-II#33]
Develop content block for main app.
(Project, Objectives and Metrics)

Expected features:
Create a Project (the user who creates the project is the owner)
Invite people to a project and set roles
Create one or many Objectives for a Project
Create one or multiple Metrics for an Objective
Input data to Metric

**Comment by ioFormigoni** [comment]
obs: some features depends on issue #30

**Comment by acremonezi** [comment]
**Classes Created:**
1. Create an Account.
2. Create one or many Projects for an Account.
3. Create one or many Objectives for a Project.
4. Create one or multiple Metrics for an Objective.

**Note:** Please I need help with the frontend.
